@Workshop.RestServer_HostAddress = http://localhost:5291

GET {{Workshop.RestServer_HostAddress}}/api/customer
Accept: application/json

###
GET {{Workshop.RestServer_HostAddress}}/api/customer/1
Accept: application/json